In [42]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
Gender = ["male", "male", "male", "male", "female", "female", "female", "female"]
height = [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75]
weight = [180, 190, 170, 165, 100, 150, 130, 150]
footsize = [12, 11, 12, 10, 6, 8, 7, 9]
le = preprocessing.LabelEncoder()
height_encoded=le.fit_transform(height)
weight_encoded=le.fit_transform(weight)
footsize_encoded=le.fit_transform(footsize)
features=list(zip(height_encoded,weight_encoded, footsize_encoded))
from sklearn.model_selection import train_test_split
features_train, features_test,label_train,label_test=train_test_split(features, footsize_encoded, test_size=0.2, random_state=40)
classifier = DecisionTreeClassifier()
classifier = classifier.fit(features_train, label_train)
predicted = classifier.predict(features_test)
print("prediction:", predicted)
from sklearn.metrics import confusion_matrix, accuracy_score
conf_mat = confusion_matrix(label_test, predicted)
print("Confusion Matrix:")
print(conf_mat)
accuracy=accuracy_score(label_test, predicted)
print("accuracy:",accuracy)

prediction: [4 4]
Confusion Matrix:
[[0 1 0]
 [0 0 0]
 [0 1 0]]
accuracy: 0.0
